import { SidebarMenu } from '../../components/SidebarMenu'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Vision Quest',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex">
          <SidebarMenu />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  )
}
