# Generated by Django 3.2.20 on 2023-08-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('brand_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('link', models.URLField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vq_app.run')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('remarks', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vq_app.run')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('image_size', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vq_app.run')),
            ],
        ),
    ]
