# Generated by Django 3.2.20 on 2023-08-04 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.RemoveField(
            model_name='media',
            name='run',
        ),
        migrations.RemoveField(
            model_name='objectresult',
            name='run',
        ),
        migrations.RemoveField(
            model_name='productresult',
            name='run',
        ),
        migrations.AlterModelTable(
            name='media',
            table='Media',
        ),
        migrations.AlterModelTable(
            name='objectresult',
            table='ObjectResult',
        ),
        migrations.AlterModelTable(
            name='productresult',
            table='ProductResult',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
        migrations.AddField(
            model_name='media',
            name='job',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='vq_app.jobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectresult',
            name='job',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='vq_app.jobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productresult',
            name='job',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='vq_app.jobs'),
            preserve_default=False,
        ),
    ]
